apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vadapav1
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kharatramesh/argocd11.git
    targetRevision: HEAD
    path: dev1
  destination: 
    server: https://kubernetes.default.svc
    namespace: project3

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
