apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app1
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app1
    spec:
      containers:
      - image: kharatramesh/vadapavimages:biryani
        name: httpd
        volumeMounts:
        - name: v1
          mountPath: /logs
  volumes:
  - name: v1
    persistentVolumeClaim:
      claimName: azure-managed-disk
